name: turbopaq_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  bson: ^5.0.4
  flutter_displaymode: ^0.6.0
  intl: ^0.17.0
  grouped_list: ^5.1.2
  calendar_date_picker2: ^1.0.2
  hexcolor: ^3.0.1
  ml_linalg: ^13.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: lib\fonts\Nunito-VariableFont_wght.ttf
          weight: 400
  assets:
   - assets/images/logo.png


